### ISSUE TITLE
Timeout Error

### ISSUE THREAD

**Issue by FaryarKankash** [VictorMRojas/g4f-ts#11]
library will return timeout on ChatBase provider and it will return null on Bing provider even when i use proxy. is this project already dead?

**Comment by VictorMRojas** [comment]
Hi, I just realized that the providers are not working properly, I am going to add more providers, while trying to fix the ones that are :)

**Comment by VictorMRojas** [comment]
The ChatBase provider seems to work, I'm aware if it's intermittent operation

**Comment by VictorMRojas** [comment]
I've updated the npm package to version 1.2.0.

This release comes with a [new provider](https://github.com/VictorMRojas/g4f-ts?tab=readme-ov-file#-providers) and [model support](https://github.com/VictorMRojas/g4f-ts?tab=readme-ov-file#-models); now you can decide which model to use, from GPT-4 to Davinci-002.

The new provider gives you access to all of these models. 
ChatBase seems to work fine (for now). 
Bing has been marked as inactive (until it's fixed).
