### ISSUE TITLE
I specify a height but it gives an error

### ISSUE THREAD

**Issue by daekydev** [VictorMRojas/g4f-ts#21]
I specify a height but it keeps getting Error: The provider option "height" must be an integer. I get the error: The value I entered is definitely a number but it keeps giving

**Comment by VictorMRojas** [comment]
Can you provide more information about this error?

**Comment by VictorMRojas** [comment]
Closed due to inactivity

**Comment by daekydev** [comment]
> Closed due to inactivity

Height and width are not working. When I enter it, it does not draw at those proportions. I told you that, I forgot to check again.

**Comment by VictorMRojas** [comment]
At this time there are no enabled providers that have the option of height and width, so I propose the following code that can help you

```ts
import G4F from "./src/G4F";
import fs from "fs";
import sharp from 'sharp';

const g4f = new G4F();
(async() => {
    const base64Image = await g4f.imageGeneration("A village", { 
        provider: g4f.providers.StableDiffusionPlus,
    });	
    const buffer = Buffer.from(base64Image, 'base64');

    fs.writeFileSync('image.jpg', buffer);

    sharp('image.jpg')
        .resize({ height: 800 }) 
        .toFile('image_resized.jpg', (err, info) => {
            if (err) return console.error(err);
            console.log('Done!');
        });
})();
```
