### ISSUE TITLE
System prompt not working

### ISSUE THREAD

**Issue by XInTheDark** [VictorMRojas/g4f-ts#23]
The text generation seems to ignore the system prompt even though it is supplied. Can you check this?
model used: chatgpt.ai gpt-4-32k

**Comment by VictorMRojas** [comment]
It seems to work well now, remember that sometimes moments of intermittency can occur, but the general behavior is very stable!

```ts
import G4F from "./src/G4F";

const g4f = new G4F();
(async() => {
    const response = await g4f.chatCompletion([{ role: "user", content: "Say something" }], { model: "gpt-4-32k" });
    console.log(response);
})();
```
