### ISSUE TITLE
Does not produce images 

### ISSUE THREAD

**Issue by daekydev** [VictorMRojas/g4f-ts#24]
Awaiting remains in the image generation process But it does not give a valid answer only in the StableDiffusionXL model, but there is no problem in normal stable diffusion.

**Comment by VictorMRojas** [comment]
Hello, there have been some changes regarding the image generation providers, please check the [new version 1.4.5](https://www.npmjs.com/package/g4f/v/1.4.5)

Some providers have been added and others have been deactivated. Check [this](https://www.npmjs.com/package/g4f/v/1.4.5#list-providers-image-generation) for more info.
