### ISSUE TITLE
Personalization feature for GPT-4 does not work 

### ISSUE THREAD

**Issue by daekydev** [VictorMRojas/g4f-ts#25]
![Screenshot_2024-05-09-22-49-56-221_com.android.chrome-edit.jpg](https://github.com/VictorMRojas/g4f-ts/assets/91830825/20161b54-2bed-4186-9e76-0c937390f036)

It's not working no matter what I do

**Comment by zachey01** [comment]
just use user role

**Comment by VictorMRojas** [comment]
Sometimes the user role works better than the system role; nevertheless, consider the following advice:

**1.** Response instructions should be placed at the top of the message, separated, written concisely, and numbered.

**2.** The text length should be appropriate for the model you are using. You cannot exceed the content that the model can handle, or else it will quickly lose context and thread of the conversation. (Example: GPT-4 model has 8K tokens, where each token equals four characters, allowing for 16,000 characters of conversation before it starts losing track).

**3.** If the content you need the model to interpret is very extensive, consider dividing it into multiple requests and verify the outcome of each request. [Check this example](https://rentry.co/f54esvux).
