### ISSUE TITLE
The Source IP / Domain contains Malware/Phishing Positives?

### ISSUE THREAD

**Issue by DJMahirNationTV** [VictorMRojas/g4f-ts#30]
![image](https://github.com/user-attachments/assets/08b9f312-ec1b-428f-9038-c739b77ffd51)
![image](https://github.com/user-attachments/assets/ed718dc0-6939-4e56-8404-7cf427b910d7)

The Source, where the Images are generated contains Malwares? Cuz the AntiVirus is blocking the access to it

**Comment by VictorMRojas** [comment]
I recently noticed that the API website started using ads that are sometimes flagged by the antivirus, that was before they changed the website to: https://nexra.aryahcr.cc/es

Considering that the API that offers the services is on the same domain as the website, it is common for them to present problems.
I do not know if the issue continues to persist with the new update of the website.
